name: Build and Deploy doc

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./out
          config_file: jsdoc.json
          template: minami
          front_page: README.md

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          target_branch: gh-pages
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
