name: Build and Deploy doc

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: "8.x"
      
      - run: npm install --save-dev jsdoc-vuejs
        
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./doc
          config_file: jsdoc.json
          template: minami
          front_page: README.md

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          target_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
